In [1]:
import numpy as np

In [2]:
minha_lista = [1, 2, 3]

In [3]:
minha_lista

[1, 2, 3]

In [4]:
np.array(minha_lista)

array([1, 2, 3])

In [5]:
minha_matriz = [[1, 2, 3],[4, 5, 6], [7, 8, 9]]

In [6]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [18]:
np.random.rand(5) * 100

array([32.26079009,  0.8661752 ,  6.18800753, 27.22869797, 93.56059279])

In [21]:
np.random.randn(4)

array([-2.03456217, -1.01436296,  1.69178765,  1.29927162])

In [22]:
np.random.randint(0, 100, 10)

array([12, 20, 19, 88,  3, 19, 12, 68, 19, 95])

In [23]:
arr = np.random.rand(25)

In [24]:
arr

array([0.83705376, 0.60880249, 0.81784583, 0.03073514, 0.62894183,
       0.75508197, 0.85933308, 0.10473519, 0.7601909 , 0.92774246,
       0.81487343, 0.52639386, 0.78619098, 0.24198899, 0.845633  ,
       0.63865398, 0.67537238, 0.95584901, 0.68765232, 0.65071282,
       0.06739401, 0.76173786, 0.01565793, 0.48087615, 0.12793022])

In [25]:
arr.reshape((5,5))

array([[0.83705376, 0.60880249, 0.81784583, 0.03073514, 0.62894183],
       [0.75508197, 0.85933308, 0.10473519, 0.7601909 , 0.92774246],
       [0.81487343, 0.52639386, 0.78619098, 0.24198899, 0.845633  ],
       [0.63865398, 0.67537238, 0.95584901, 0.68765232, 0.65071282],
       [0.06739401, 0.76173786, 0.01565793, 0.48087615, 0.12793022]])

In [26]:
arr = arr.reshape((5,5))

In [27]:
arr

array([[0.83705376, 0.60880249, 0.81784583, 0.03073514, 0.62894183],
       [0.75508197, 0.85933308, 0.10473519, 0.7601909 , 0.92774246],
       [0.81487343, 0.52639386, 0.78619098, 0.24198899, 0.845633  ],
       [0.63865398, 0.67537238, 0.95584901, 0.68765232, 0.65071282],
       [0.06739401, 0.76173786, 0.01565793, 0.48087615, 0.12793022]])

In [28]:
arr.shape

(5, 5)

In [29]:
arr.max()

0.9558490117603302

In [30]:
arr.min()

0.015657925801434214

In [31]:
arr.argmax()

17

In [32]:
arr.argmin()

22